#!/bin/sh
# Garage initialization script — runs inside the garage container via docker exec.
# Usage: docker exec <garage-container> /bin/sh /setup.sh <bucket-name>
set -e

BUCKET="${1:?Usage: setup.sh <bucket-name>}"

echo "Waiting for Garage to be ready..."
i=0
until /garage status >/dev/null 2>&1; do
  i=$((i+1))
  if [ "$i" -ge 120 ]; then
    echo "Garage not ready after 120s"; exit 1
  fi
  sleep 1
done
echo "Garage is ready."

# Get node ID (short form)
NODE_ID=$(/garage status 2>/dev/null | grep -oE '^[0-9a-f]{16}' | head -1)
if [ -z "$NODE_ID" ]; then
  echo "Could not get node ID"; exit 1
fi
echo "Node: $NODE_ID"

# Assign layout if not already assigned
if /garage status 2>/dev/null | grep -q "NO ROLE ASSIGNED"; then
  /garage layout assign -z dc1 -c 1G "$NODE_ID" 2>/dev/null
  /garage layout apply --version 1 2>/dev/null
  echo "Layout applied."
else
  echo "Layout already configured."
fi

# Create bucket (ignore if exists)
/garage bucket create "$BUCKET" 2>/dev/null || echo "Bucket '$BUCKET' already exists."

# Create key (ignore if exists)
KEY_OUTPUT=$(/garage key create annales-app-key 2>/dev/null || echo "")
if echo "$KEY_OUTPUT" | grep -q "Key name: annales-app-key"; then
  ACCESS_KEY=$(echo "$KEY_OUTPUT" | grep "Key ID:" | awk '{print $3}')
  SECRET_KEY=$(echo "$KEY_OUTPUT" | grep "Secret key:" | awk '{print $3}')
  echo ""
  echo "============================================"
  echo "New S3 credentials generated by Garage:"
  echo "  S3_ACCESS_KEY=$ACCESS_KEY"
  echo "  S3_SECRET_KEY=$SECRET_KEY"
  echo "Update your .env file with these values!"
  echo "============================================"
else
  # Key already exists, get its ID
  ACCESS_KEY=$(/garage key list 2>/dev/null | grep "annales-app-key" | awk '{print $1}')
  echo "Key already exists: $ACCESS_KEY"
fi

# Grant key access to bucket
if [ -n "$ACCESS_KEY" ]; then
  /garage bucket allow --read --write --owner "$BUCKET" --key "$ACCESS_KEY" 2>/dev/null || true
  echo "Permissions granted."
fi

echo "Bucket '$BUCKET' ready."
